from iris.fileformats.pp import STASH


class StashMap(dict):
    """
    """

    def remap_cube(self, cube):
        stash = cube.attributes['STASH']
        self[stash].modify_cube(cube)

    def remap_cubelist(self, cubelist):
        for cube in cubelist:
            stash = cube.attributes['STASH']
            if stash in self:
                self[stash].modify_cube(cube)


class CustomStash(object):
    """Defines attributes to add to a cube based on the STASH attribute

    Attributes:
        name

        units
    """

    def __init__(self, name=None, units=None):
        self.name = name
        self.units = units

    def modify_cube(self, cube):
        # Change Units
        cube.convert_units(self.units)

        # Change name
        cube.rename(self.name)


# Custom stash for MetUM prognostic variables
met_um = StashMap(
    [(STASH(1, 0, 253), CustomStash(name='air_density_times_r_squared',
                                    units='kg m-1'))])

# NDdiag stash mappings
nddiag = StashMap(
    [(STASH(1, 90, 1), CustomStash(name='geopotential_height',
                                   units='m')),
     (STASH(1, 90, 2), CustomStash(name='temperature',
                                   units='K')),
     (STASH(1, 90, 3), CustomStash(name='u_component_of_wind',
                                   units='m s-1')),
     (STASH(1, 90, 4), CustomStash(name='v_component_of_wind',
                                   units='m s-1')),
     (STASH(1, 90, 5), CustomStash(name='ice_relative_humidity',
                                   units='percent')),
     (STASH(1, 90, 6), CustomStash(name='potential_temperature',
                                   units='K')),
     (STASH(1, 90, 7), CustomStash(name='equivalent_potential_temperature',
                                   units='K')),
     (STASH(1, 90, 8), CustomStash(name='density',
                                   units='Kg m-3')),
     (STASH(1, 90, 9), CustomStash(name='humidity_mixing_ratio',
                                   units='')),
     (STASH(1, 90, 10), CustomStash(name='sat_eq_pot_temp',
                                    units='K')),
     (STASH(1, 90, 11), CustomStash(name='du_dp',
                                    units='m s-1 Pa-1')),
     (STASH(1, 90, 12), CustomStash(name='dv_dp',
                                    units='m s-1 Pa-1')),
     (STASH(1, 90, 13), CustomStash(name='dtheta_dp',
                                    units='K Pa-1')),
     (STASH(1, 90, 14), CustomStash(name='dtheta_e_dp',
                                    units='K Pa-1')),
     (STASH(1, 90, 15), CustomStash(name='div_v',
                                    units='K Pa-1')),
     (STASH(1, 90, 16), CustomStash(name='dry_pv',
                                    units='K m2 kg-1 s-1')),
     (STASH(1, 90, 17), CustomStash(name='moist_pv',
                                    units='K m2 kg-1 s-1')),
     (STASH(1, 90, 18), CustomStash(name='geostropic_u_wind',
                                    units='m s-1')),
     (STASH(1, 90, 19), CustomStash(name='geostrophic_v_wind',
                                    units='m s-1')),
     (STASH(1, 90, 20), CustomStash(name='wind_strength',
                                    units='m s-1')),
     (STASH(1, 90, 21), CustomStash(name='q1',
                                    units='K m-1 s-1')),
     (STASH(1, 90, 22), CustomStash(name='q2',
                                    units='K m-1 s-1')),
     (STASH(1, 90, 23), CustomStash(name='div_q',
                                    units='K m-2 s-1')),
     (STASH(1, 90, 24), CustomStash(name='absolute_vorticity',
                                    units='s-1')),
     (STASH(1, 90, 25), CustomStash(name='vertical_velocity',
                                    units='m s-1')),
     (STASH(1, 90, 28), CustomStash(name='dug_dp',
                                    units='m s-1 Pa-1')),
     (STASH(1, 90, 29), CustomStash(name='dvg_dp',
                                    units='m s-1 Pa-1')),
     (STASH(1, 90, 31), CustomStash(name='mag_geo_defmn',
                                    units='')),
     (STASH(1, 90, 32), CustomStash(name='u_cpt_gedef_axis',
                                    units='s-1')),
     (STASH(1, 90, 33), CustomStash(name='v_cpt_gedef_axis',
                                    units='s-1')),
     (STASH(1, 90, 34), CustomStash(name='mag_grad_thw',
                                    units='K m-1')),
     (STASH(1, 90, 35), CustomStash(name='u_cpt_grad_thw',
                                    units='K m-1')),
     (STASH(1, 90, 36), CustomStash(name='v_cpt_grad_thw',
                                    units='K m-1')),
     (STASH(1, 90, 37), CustomStash(name='geo_defmn_wrt_theta_w',
                                    units='s-1')),
     (STASH(1, 90, 38), CustomStash(name='relative_vorticity',
                                    units='s-1')),
     (STASH(1, 90, 39), CustomStash(name='geostrophic_relative_vorticity',
                                    units='s-1')),
     (STASH(1, 90, 40), CustomStash(name='wind_direction',
                                    units='degrees')),
     (STASH(1, 90, 41), CustomStash(name='theta_w',
                                    units='K')),
     (STASH(1, 90, 42), CustomStash(name='ageostrophic_u_wind',
                                    units='m s-1')),
     (STASH(1, 90, 43), CustomStash(name='ageostrophic_v_wind',
                                    units='m s-1')),
     (STASH(1, 90, 44), CustomStash(name='mag_grad_th',
                                    units='K m-1')),
     (STASH(1, 90, 45), CustomStash(name='u_cpt_grad_th',
                                    units='K m-1')),
     (STASH(1, 90, 46), CustomStash(name='v_cpt_grad_th',
                                    units='K m-1')),
     (STASH(1, 90, 55), CustomStash(name='qg_w_from_invlap_minus_2divq',
                                    units='m s-1')),
     (STASH(1, 90, 58), CustomStash(name='qg_w_from_800-600mb_invlap_minus_2divq',
                                    units='m s-1')),
     (STASH(1, 90, 59), CustomStash(name='qg_w_from_600-100mb_invlap_minus_2divq',
                                    units='m s-1')),
     (STASH(1, 90, 60), CustomStash(name='qg_w_from_1000-800mb_invlap_minus_2divq',
                                    units='m s-1')),

     # Front Parameters Hewson (1998)
     (STASH(1, 90, 61), CustomStash(name='front_locator_parameter_thw',
                                    units='K m-3')),
     (STASH(1, 90, 62), CustomStash(name='thermal_front_parameter_thw',
                                    units='K m-2')),
     (STASH(1, 90, 63), CustomStash(name='front_-delsqd',
                                    units='K m-2')),
     (STASH(1, 90, 64), CustomStash(name='local_frontal_gradient_thw',
                                    units='K m-1')),
     (STASH(1, 90, 65), CustomStash(name='front_speed_thw',
                                    units='m s-1')),
     (STASH(1, 90, 66), CustomStash(name='theta_w_advection',
                                    units='K s-1')),
     (STASH(1, 90, 67), CustomStash(name='geostrophic_theta_w_advection',
                                    units='K s-1')),
     (STASH(1, 90, 68), CustomStash(name='front_locator_parameter_th',
                                    units='K m-3')),
     (STASH(1, 90, 69), CustomStash(name='thermal_front_parameter_th',
                                    units='K m-2')),
     (STASH(1, 90, 70), CustomStash(name='front_-delsqd_th',
                                    units='K m-2')),
     (STASH(1, 90, 71), CustomStash(name='local_frontal_gradient_th',
                                    units='K m-1')),
     (STASH(1, 90, 72), CustomStash(name='front_speed_th',
                                    units='m s-1')),
     (STASH(1, 90, 73), CustomStash(name='theta_advection',
                                    units='K s-1')),
     (STASH(1, 90, 74), CustomStash(name='geostrophic_theta_advection',
                                    units='K s-1')),

     (STASH(1, 90, 75), CustomStash(name='shear_relative_vorticity',
                                    units='s-1')),
     (STASH(1, 90, 76), CustomStash(name='jet_angle',
                                    units='degrees')),
     (STASH(1, 90, 77), CustomStash(name='specific_humidity',
                                    units='Kg Kg-1')),
     (STASH(1, 90, 80), CustomStash(name='frontal_waves',
                                    units='K^2 m-3 s-1')),
     (STASH(1, 90, 81), CustomStash(name='f1_vector',
                                    units='K m-1 s-1')),
     (STASH(1, 90, 82), CustomStash(name='f2_vector',
                                    units='K m-1 s-1')),
     (STASH(1, 90, 83), CustomStash(name='frontogenesis_tilt',
                                    units='K^2 m-2 s-1')),
     (STASH(1, 90, 84), CustomStash(name='frontogenesis_function',
                                    units='K^2 m-2 s-1')),
     (STASH(1, 90, 85), CustomStash(name='u_wind_westerly',
                                    units='m s-1')),
     (STASH(1, 90, 86), CustomStash(name='v_wind_westerly',
                                    units='m s-1')),
     (STASH(1, 90, 87), CustomStash(name='omega_from_w_wind_at_hse',
                                    units='Pa s-1')),
     (STASH(1, 90, 88), CustomStash(name='dry_static_stability',
                                    units='s-2')),
     (STASH(1, 90, 89), CustomStash(name='moist_static_stability',
                                    units='s-2')),
     (STASH(1, 90, 90), CustomStash(name='dry_richardson_no',
                                    units='')),
     (STASH(1, 90, 91), CustomStash(name='moist_richardson_no',
                                    units='')),
     (STASH(1, 90, 96), CustomStash(name='cloud_liquid_water',
                                    units='kg kg-1')),
     (STASH(1, 90, 97), CustomStash(name='cloud_ice',
                                    units='kg-1')),
     (STASH(1, 90, 98), CustomStash(name='pseudo_adiabatic_capep',
                                    units='J Kg!e-1!n')),
     (STASH(1, 90, 99), CustomStash(name='reversible_caper',
                                    units='J Kg!e-1!n')),
     (STASH(1, 90, 99), CustomStash(name='saturated_downdraft_dcape',
                                    units='J Kg!e-1!n')),
     (STASH(1, 90, 101), CustomStash(name='lat_lon_on_rotated_and_true_grids',
                                     units='')),
     (STASH(1, 90, 102), CustomStash(name='geostropic_dry_pv',
                                     units='K Kg-1 m s-2')),
     (STASH(1, 90, 103), CustomStash(name='geostropic_moist_pv',
                                     units='K Kg-1 m s-2')),
     (STASH(1, 90, 104), CustomStash(name='magnitude_of_the_vector_wind_shear',
                                     units='m s-1 Pa-1')),
     (STASH(1, 90, 107), CustomStash(name='saturated_moist_pv',
                                     units='K Kg-1 m s-2')),
     (STASH(1, 90, 115), CustomStash(name='pseudo_adiabatic_positive_area_pap',
                                     units='J Kg!e-1!n')),
     (STASH(1, 90, 116), CustomStash(name='pseudo_adiabatic_nap_cin',
                                     units='J Kg!e-1!n')),
     (STASH(1, 90, 117), CustomStash(name='reversible_positive_area_par',
                                     units='J Kg!e-1!n')),
     (STASH(1, 90, 118), CustomStash(name='reversible_cin',
                                     units='J Kg!e-1!n')),
     (STASH(1, 90, 119), CustomStash(name='theta_s',
                                     units='K')),
     (STASH(1, 90, 120), CustomStash(name='surface_pressure',
                                     units='Pa')),
     (STASH(1, 91, 1), CustomStash(name='moisture_flux_cgence_integrated_div_vq',
                                   units='')),
     (STASH(1, 91, 2), CustomStash(name='vertically_integrated_q_div_v_rho_dz',
                                   units='')),
     (STASH(1, 90, 3), CustomStash(name='vertically_integrated_div_vq_-_q_div_v',
                                   units=''))
     ])

# Potential temperature tracers at vn7.3
theta_tracers = StashMap(
    [(STASH(1, 0, 321), CustomStash(name='advection_only_theta',
                                    units='K')),
     (STASH(1, 0, 322), CustomStash(name='short_wave_radiation_theta',
                                    units='K')),
     (STASH(1, 0, 323), CustomStash(name='long_wave_radiation_theta',
                                    units='K')),
     (STASH(1, 0, 324), CustomStash(name='radiation_theta',
                                    units='K')),
     (STASH(1, 0, 325), CustomStash(name='microphysics_theta',
                                    units='K')),
     (STASH(1, 0, 326), CustomStash(name='',
                                    units='K')),
     (STASH(1, 0, 327), CustomStash(name='convection_theta',
                                    units='K')),
     (STASH(1, 0, 328), CustomStash(name='',
                                    units='K')),
     (STASH(1, 0, 329), CustomStash(name='theta',
                                    units='K')),
     (STASH(1, 0, 330), CustomStash(name='boundary_layer_latent_heating_theta',
                                    units='K')),
     (STASH(1, 0, 331), CustomStash(name='boundary_layer_theta',
                                    units='K')),
     (STASH(1, 0, 332), CustomStash(name='atmospheric_physics_1_theta',
                                    units='K')),
     (STASH(1, 0, 333), CustomStash(name='atmospheric_physics_2_theta',
                                    units='K')),
     (STASH(1, 0, 334), CustomStash(name='diffusion_theta',
                                    units='K')),
     (STASH(1, 0, 335), CustomStash(name='time_filtering_theta',
                                    units='K')),
     (STASH(1, 0, 336), CustomStash(name='update_fields_theta',
                                    units='K')),
     (STASH(1, 0, 337), CustomStash(name='advection_theta',
                                    units='K')),
     (STASH(1, 0, 338), CustomStash(name='lateral_boundary_theta',
                                    units='K')),
     (STASH(1, 0, 339), CustomStash(name='cloud_rebalancing_theta',
                                    units='K')),
     (STASH(1, 0, 340), CustomStash(name='polar_filtering_theta',
                                    units='K')),
     (STASH(1, 0, 342), CustomStash(name='pressure_gradient_theta',
                                    units='K')),
     (STASH(1, 0, 343), CustomStash(name='pressure_solver_theta',
                                    units='K')),
     (STASH(1, 0, 344), CustomStash(name='continuity_theta',
                                    units='K')),
     (STASH(1, 0, 345), CustomStash(name='idealised_pressure_forcing_theta',
                                    units='K')),
     (STASH(1, 0, 346), CustomStash(name='barotropic_friction_theta',
                                    units='K')),
     (STASH(1, 0, 347), CustomStash(name='baroclinic_friction_theta',
                                    units='K')),
     ])

# PV tracers at vn7.3
pv_tracers = StashMap(
    [(STASH(1, 0, 321), CustomStash(name='advection_only_pv',
                                    units='PVU')),
     (STASH(1, 0, 322), CustomStash(name='short_wave_radiation_pv',
                                    units='PVU')),
     (STASH(1, 0, 323), CustomStash(name='long_wave_radiation_pv',
                                    units='PVU')),
     (STASH(1, 0, 324), CustomStash(name='radiation_pv',
                                    units='PVU')),
     (STASH(1, 0, 325), CustomStash(name='microphysics_pv',
                                    units='PVU')),
     (STASH(1, 0, 326), CustomStash(name='gravity_wave_drag_pv',
                                    units='PVU')),
     (STASH(1, 0, 327), CustomStash(name='convection_pv',
                                    units='PVU')),
     (STASH(1, 0, 328), CustomStash(name='',
                                    units='PVU')),
     (STASH(1, 0, 329), CustomStash(name='',
                                    units='PVU')),
     (STASH(1, 0, 330), CustomStash(name='boundary_layer_pv',
                                    units='PVU')),
     (STASH(1, 0, 331), CustomStash(name='advection_only_theta',
                                    units='K')),
     (STASH(1, 0, 332), CustomStash(name='atmospheric_physics_1_pv',
                                    units='PVU')),
     (STASH(1, 0, 333), CustomStash(name='atmospheric_physics_2_pv',
                                    units='PVU')),
     (STASH(1, 0, 334), CustomStash(name='pressure_solver_pv',
                                    units='PVU')),
     (STASH(1, 0, 335), CustomStash(name='',
                                    units='PVU')),
     (STASH(1, 0, 336), CustomStash(name='dynamics_tracer_inconsistency',
                                    units='PVU')),
     (STASH(1, 0, 337), CustomStash(name='',
                                    units='PVU')),
     (STASH(1, 0, 338), CustomStash(name='',
                                    units='K')),
     (STASH(1, 0, 339), CustomStash(name='cloud_rebalancing_pv',
                                    units='PVU')),
     (STASH(1, 0, 340), CustomStash(name='ertel_potential_vorticity',
                                    units='PVU')),
     ])
